#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: istio-operator
  labels:
    chart_group: istio-charts
spec:
  releaseName: istio-istio-operator 
  chart:
    spec:
      chart: istio-operator 
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: istio-operator-static-overrides
      valuesKey: istio-operator-static-overrides.yaml
    - kind: Secret
      name: istio-operator-system-overrides
      valuesKey: istio-operator-system-overrides.yaml
