#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: istio-system
resources:
  - helmrelease.yaml
  - istio-operator.yaml
secretGenerator:
  - name: istio-operator-static-overrides
    files:
      - istio-operator-static-overrides.yaml
  - name: istio-operator-system-overrides
    files:
      - istio-operator-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
