#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: kiali-server
  labels:
    chart_group: istio-charts
spec:
  releaseName: istio-kiali-server 
  chart:
    spec:
      chart: kiali-server 
      version: 1.45.0 
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: kiali-server-static-overrides
      valuesKey: kiali-server-static-overrides.yaml
    - kind: Secret
      name: kiali-server-system-overrides
      valuesKey: kiali-server-system-overrides.yaml
