#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: istio-system 
resources:
  - helmrelease.yaml
secretGenerator:
  - name: kiali-server-static-overrides
    files:
      - kiali-server-static-overrides.yaml
  - name: kiali-server-system-overrides
    files:
      - kiali-server-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
